### ISSUE TITLE
Naming scheme has changed for watchexec downloads

### ISSUE THREAD

**Issue by aardvarkk** [nyrst/asdf-watchexec#1]
The plugin is broken for versions of watchexec > 1.15.3. Watchexec has now split into separate `cli` and `lib` versions.

The plugin is trying to download, for instance, `watchexec-cli-v1.17.1-x86_64-unknown-linux-gnu.tar.xz` (because that's the version tag -- this would have worked before the split into two flavours),  but the artifacts on github are named `https://github.com/watchexec/watchexec/releases/download/cli-v1.17.1/watchexec-1.17.1-x86_64-unknown-linux-gnu.tar.xz`.

Notice the lack of `cli` in the filename there, because I guess the artifacts are always assuming you're using the CLI version.

A workaround is to downgrade to 1.15.3.

I'm not entirely sure of the best path forward to fix this -- it looks like you probably don't have much choice but to try to split the version string up a bit and trim out the `cli-` part when determining the download location?

**Comment by SiegfriedEhret** [comment]
Thanks @aardvarkk, I'll look into that tomorrow, there should be some semver bash function on the internet I can use (I am quite lazy these days) to choose the relevant url scheme.

**Comment by SiegfriedEhret** [comment]
Should be fixed now, it works on my computer ™️ .
Let me know if you have any issue.

Cheers!

**Comment by aardvarkk** [comment]
@SiegfriedEhret Yes -- it works for me too. Thanks so much for the update!
