### ISSUE TITLE
macOS: install x86_64 binary on arm macs

### ISSUE THREAD

**Issue by pesterhazy** [nyrst/asdf-watchexec#2]
It seems like this installs an intel binary on arm macs

```
 % file $(asdf which watchexec)
/Users/user/.asdf/installs/watchexec/1.20.5/bin/watchexec: Mach-O 64-bit executable x86_64
```

Is it possible to provide arm binaries, which should be faster?

Unfortunately I don't see arm binaries prebuilt on github https://github.com/watchexec/watchexec/releases

**Comment by SiegfriedEhret** [comment]
Hello @pesterhazy,
Thanks for raising this issue and sorry for the late reply.
I was just looking at the last release https://github.com/watchexec/watchexec/releases/tag/v1.22.3 and binaries for arm macs (aarch64) are provided. 
I will try to look into that later this week, or you can send a PR if you feel adventurous :).
Cheers!

**Comment by pesterhazy** [comment]
Gave it a shot

Untested on Linux. Logic mostly stolen from https://gitlab.com/wt0f/asdf-ripgrep/-/blob/master/bin/install?ref_type=heads

**Comment by SiegfriedEhret** [comment]
Thank you very much. Sadly I can't test on Linux either.
